version: '3.8'

services:
  # 1. Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: pme_scoring_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_segura_postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pme_scoring_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Sua Aplicação Spring Boot
  app:
    image: pme-scoring:local
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spring_boot_app
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=pme_scoring_db
      - DB_USER=postgres
      - DB_PASSWORD=senha_segura_postgres
      - DB_DDL_AUTO=update
      - SHOW_SQL=true
      - FORMAT_SQL=true
      - SERVER_PORT=8080
      - LOG_PATH=/app/logs
      - JWT_SECRET=sua_chave_secreta_jwt_super_segura_aqui
      - SOURCE_ID=docker-env
      - ADMIN_DEFAULT_EMAIL=admin@admin.com
      - ADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net

volumes:
  pgdata:
    driver: local

networks:
  app-net:
    driver: bridge